---
- hosts: wordpress-hosts
  vars:
    wp_admin_pw: "{{ lookup('env','WP_ADMIN_PW') }}"
  remote_user: deploy

  tasks:

  - name: Make /var/www/html and its subdirectories writable by anyone in www-data group
    shell: chmod -R 775 /var/www/html
    become: true

  # ? For this to work, you must have logged into the new host as root using ssh:
  - name: Install WordPress tables into MySQL
    shell: wp
      --path=/var/www/html
      --url=http://blog.bbs-software.com
      --title="Keith R. Bennett's Technical Blog"
      --admin_user=keithrbennett
      --admin_password="{{ wp_admin_pw }}"
      --admin_email=bad-email@bad-domain.com
      core install
    become: yes
    become_user: www-data

  - name: Set owner/group of /var/www/html tree to www-data.
    shell: chown -R www-data:www-data /var/www/html
    become: true

  - name: Update WordPress installation
    shell: wp --path=/var/www/html core update && wp --path=/var/www/html core update-db
    become: yes
    become_user: www-data


  - name: Update WordPress plugins
    shell: wp --path=/var/www/html plugin --all update
    become: yes
    become_user: www-data


  - name: Update WordPress theme
    shell: wp --path=/var/www/html theme --all update
    become: yes
    become_user: www-data


  - name: Set owner/group of /var/www/html tree to www-data.
    shell: chown -R www-data:www-data /var/www/html
    become: true

  - name: Get status of original-content.xml
    stat:  path=/home/deploy/downloads/original-content.xml
    register: original_content

  - name: Copy XML file to remote
    copy:
      src: data/current.xml   # current.xml s/b symlinked to the appropriate file
      dest: /home/deploy/downloads/original-content.xml
    when: not original_content.stat.exists

  - name: Install & activate WordPress importer
    shell: wp plugin install wordpress-importer --activate && touch ~/ansible-flags/install-wp-importer
    args:
      creates: ~/ansible-flags/install-wp-importer

  - name: Set owner/group of /var/www/html tree to www-data.
    shell: chown -R www-data:www-data /var/www/html
    become: true

  - name: Import it into WordPress
    shell: wp --authors=create import /home/deploy/downloads/original-content.xml
           && touch ~/ansible-flags/wp-data-imported
    args:
      creates: ~/ansible-flags/wp-data-imported
