---
- hosts: wordpress-hosts
  vars:
  remote_user: deploy

  tasks:

  - name: See if it's already at its destination.
    stat: path=/usr/local/bin/wp
    register: wp

  - name: Download WordPress Command Line utility
    get_url:
      url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
      dest: /home/deploy/downloads
    when: not wp.stat.exists

  - name: Set WP-CLI executable bit
    file: path=/home/deploy/downloads/wp-cli.phar  mode="u=rwx,g=rx,o=rx"
    when: not wp.stat.exists

  - name: Copy to destination if not already there.
    become: true
    command: cp  /home/deploy/downloads/wp-cli.phar  /usr/local/bin/wp
    when: not wp.stat.exists


# Set up configuration file.

  - name: Get stat of config file.
    stat: path=/home/deploy/.wp-cli/config.yml
    register: config_file

  - name: Create WP CLI control directory if needed
    file: path=~/.wp-cli  state=directory
    when: not config_file.stat.exists

  - name: Copy config file if needed.
    copy: src=data/wp-cli-config.yml  dest=/home/deploy/.wp-cli/config.yml
    when: not config_file.stat.exists
