---
- hosts: wordpress-hosts
  vars:
    dirs_to_make_writable: "/var/www/html  /var/www/html/wp-admin  /var/www/html/wp-content  /var/www/html/wp-includes"
    wp_admin_pw: "{{ lookup('env','HOME') }}"
  remote_user: deploy

  tasks:

  - name: Make /var/www/html and its subdirectories writable by anyone in www-data group
    shell: find /var/www/html -type d -exec chmod 775 {} ";"
           && touch /home/deploy/ansible-flags/make-html-writable
    become: true
    args:
      creates: /home/deploy/ansible-flags/make-html-writable

  # ? For this to work, you must have logged into the new host as root using ssh:
  - name: Install WordPress tables into MySQL
    shell: wp
      --path=/var/www/html
      --url=http://blog.bbs-software.com
      --title="Keith R. Bennett's Technical Blog"
      --admin_user=keithrbennett
      --admin_password="{{ wp_admin_pw }}"
      --admin_email=bad-email@bad-domain.com
      core install && touch ~/ansible-flags/install-wp
    args:
      creates: ~/ansible-flags/install-wp

  - name: Get status of original-content.xml
    stat:  path=/home/deploy/downloads/original-content.xml
    register: original_content

  - name: Copy XML file to remote
    copy:
      src: data/keithrbennett039stechnicalblog.wordpress.2016-05-07.xml
      dest: /home/deploy/downloads/original-content.xml
    when: not original_content.stat.exists

  - name: Install & activate WordPress importer
    shell: wp plugin install wordpress-importer --activate && touch ~/ansible-flags/install-wp-importer
    args:
      creates: ~/ansible-flags/install-wp-importer

  - name: Import it into WordPress
    shell: wp --authors=create import /home/deploy/downloads/original-content.xml
           && touch ~/ansible-flags/wp-data-imported
    args:
      creates: ~/ansible-flags/wp-data-imported
