---
- hosts: wordpress-hosts
  vars:
  remote_user: deploy

  tasks:

  - name: Copy XML file to remote
    copy: src=data/keithrbennett039stechnicalblog.wordpress.2016-05-07.xml  dest=/home/deploy/original-content.xml



