---
- hosts: wordpress-hosts
  vars:
  remote_user: deploy

  tasks:

  - name: Copy Themeforest Jupiter WordPress theme to host
    copy: src=~/software/themeforest-5177775-jupiter-multipurpose-responsive-theme-wordpress-theme.zip
          dest=~/downloads/jupiter-theme.zip

  - name: Install Jupiter theme
    shell: wp theme install ~/downloads/jupiter-theme.zip --activate
    args:
      creates: /var/www/html/wp-content/themes/jupiter

  - name: Set owner/group of /var/www/html tree to www-data.
    shell: chown -R www-data:www-data /var/www/html
    become: true

