---
- hosts: wordpress-hosts
  vars:
  remote_user: deploy

  tasks:

  - name: Copy Themeforest Jupiter WordPress theme to host
    copy: src=~/software/themeforest-5177775-jupiter-multipurpose-responsive-theme-wordpress-theme.zip
          dest=~/downloads/jupiter-theme.zip

  - name: Install Jupiter theme
    shell: wp theme is-installed jupiter && echo ThemeAlreadyInstalled || wp --activate theme install ~/downloads/jupiter-theme.zip --activate
    register: cmd_result
    changed_when: cmd_result.stdout != "ThemeAlreadyInstalled"

  - name: Set owner/group of /var/www/html tree to www-data.
    shell: chown -R www-data:www-data /var/www/html
    become: true

  # The following 2 steps are identical except for the plugin name.
  # I'm using items so that the shell command is identical.

  - name: Install plugin artbees-captcha
    shell: wp plugin is-installed {{ item }} && echo already_installed || wp plugin install {{ item }}
    with_items:
      -  artbees-captcha
    register: cmd_result
    changed_when: cmd_result.stdout != "already_installed"

  - name: Install plugin js_composer_theme
    shell: (wp plugin is-installed {{ item }} && echo already_installed) || wp plugin install {{ item }}
    with_items:
      -  js_composer_theme
    register: cmd_result
    changed_when: cmd_result.stdout != "already_installed"
