---
- hosts: wordpress-hosts
  vars:
  remote_user: deploy

  tasks:

  - name: Copy activello WordPress theme to host
    get_url: url=https://downloads.wordpress.org/theme/activello.1.3.1.zip
          dest=~/downloads/activello.1.3.1.zip


  - name: Install and Activate Activello theme
    shell: wp theme is-installed activello && echo ThemeAlreadyInstalled || wp --activate theme install ~/downloads/activello.1.3.1.zip --activate
    register: cmd_result
    changed_when: cmd_result.stdout != "ThemeAlreadyInstalled"

  - name: Install plugin syntaxhighlighter
    shell: (wp plugin is-installed syntaxhighlighter && echo already_installed)
           || wp plugin install --activate syntaxhighlighter
    register: cmd_result
    changed_when: cmd_result.stdout != "already_installed"

  # Can set this to run if any previous step fails?
  - name: Set owner/group of /var/www/html tree to www-data.
    shell: chown -R www-data:www-data /var/www/html
    become: true

  - name: Delete 'hello, world' post
    shell: if (wp post list | grep "^1.*hello-world") then echo present; wp post delete 1; fi
    register: status
    changed_when: status.stdout == 'present'
