---
- hosts: wordpress-hosts
  vars:
  remote_user: deploy

  tasks:

  - name: Copy Themeforest Jupiter WordPress theme to host
    copy: src=~/software/themeforest-5177775-jupiter-multipurpose-responsive-theme-wordpress-theme.zip
          dest=~/downloads/jupiter-theme.zip

  - name: Install Jupiter theme
    shell: wp theme install ~/downloads/jupiter-theme.zip --activate
           && touch ~/ansible-flags/install-jupiter-theme
    args:
      creates: ~/ansible-flags/install-jupiter-theme
