---
- hosts: wordpress-hosts
  vars:
  remote_user: deploy

  tasks:

  - name: Get Ruby status
    stat: path=/usr/bin/ruby
    register: ruby

  - name: Add Brightbox Ubuntu repository
    apt_repository: repo=ppa:brightbox/ruby-ng
    become: true
    when: not ruby.stat.exists

  - name: Install Ruby
    apt: update_cache=yes  name=ruby2.4,ruby2.4-dev  state=latest
    become: true
    when: not ruby.stat.exists

  - name: Install gem build prerequisites
    apt:  name=build-essential,make  state=latest
    become: true
